version: '3.8'

services:
  mysql:
    image: mysql:8.1
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ms_error_tracker
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  zookeeper:
    image: bitnami/zookeeper:3.8.1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.5.1
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"

  error-tracker:
    build: .
    image: yourdockerhubuser/ms-error-tracker:latest
    depends_on:
      - mysql
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ms_error_tracker
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=8084
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_ERROR_TOPIC=fhir-error-topic
    ports:
      - "8084:8084"

volumes:
  mysql-data:
